// Generated by CoffeeScript 1.8.0
var Expenses;

if (Meteor.isClient) {
  Expenses = Mongo.Collection('expenses');
  Session.set('loginMessage', null);
  Template.login.helpers({
    'loginMessage': function() {
      return Session.get('loginMessage');
    }
  });
  Template.login.events = {
    'click button': function() {
      var email, password;
      email = $('#email').val();
      password = $('#password').val();
      return Meteor.loginWithPassword(email, password, function(error) {
        if (error) {
          return Session.set('loginMessage', error.reason);
        } else {
          return Session.set('loginMessage', 'Welcome' + Meteor.user().profile.name);
        }
      });
    }
  };
}

//# sourceMappingURL=client.js.map
